### PR TITLE
erroranalysis v0.5.3 - Match Grayskull Source

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes https://github.com/conda-forge/erroranalysis-feedstock/pull/20
closes https://github.com/conda-forge/erroranalysis-feedstock/pull/21
closes https://github.com/conda-forge/erroranalysis-feedstock/pull/22
closes https://github.com/conda-forge/erroranalysis-feedstock/pull/23

Temporary patch - till merged PR https://github.com/microsoft/responsible-ai-toolbox/issues/2475 is released in the next version of error analysis - As Error Analysis 0.5.3 dependency is blocking release of responsibleAI v0.33.0

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'requirements-object-detection.txt

**Comment by rxm7706** [comment]
@conda-forge-admin, please restart ci

**Comment by rxm7706** [comment]
@sugatoray @bgalvao @janjagusch 
Included a temporary patch to source recipe/requirements-object-detection.txt and get the feedstock to build. 
Error Analysis is required to get responsibleai v0.33.0 feedstock working again. 
Could you please review and merge. 
Thank you and regards.

**Comment by sugatoray** [comment]
@rxm7706 I will review it. I took a look at the upstream repository and found that they have the `requirements-object-detection.txt` file added there in the `MANIFEST.in` file as well. So, it should be in principle part of the `tar.gz` source file on PyPI.

I will check further, but why did you need to copy the `requirements-object-detection.txt` file (when it is supposed to be there already)?

**Comment by rxm7706** [comment]
> @rxm7706 I will review it. I took a look at the upstream repository and found that they have the `requirements-object-detection.txt` file added there in the `MANIFEST.in` file as well. So, it should be in principle part of the `tar.gz` source file on PyPI.
> 
> I will check further, but why did you need to copy the `requirements-object-detection.txt` file (when it is supposed to be there already)?

Thanks @sugatoray - I added the PR to include requirements-object-detection.txt into the manifest - it's been merged into main - but a release / upload to pypi has not been done since the merge. 

For reference 
https://github.com/microsoft/responsible-ai-toolbox/blob/main/erroranalysis/MANIFEST.in  Main
vs
https://pypi.org/project/erroranalysis/0.5.3/ -  Released: Dec 22, 2023 
or
https://github.com/microsoft/responsible-ai-toolbox/pull/2468 - Merge for Release erroranalysis v0.5.3 : Dec 22, 2023
vs manifest update PR on main
https://github.com/microsoft/responsible-ai-toolbox/pull/2476 - Merged : Dec 28, 2023

- take a look at the description of this PR and hopefully that clarifies why we need a temporary patch... 
Thanks & Regards.

**Comment by sugatoray** [comment]
@rxm7706 Thank you for the clarification. I will review it and share my review comments. If all checks out, will merge it.

**Pull request merged**
